import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Button, Grid } from '@mui/material'
import MetamaskButton from '../components/MetamaskButton'
import WalletAddress from '../components/WalletAddress'
import ConnectWalletGrid from '../components/ConnectWalletGrid'
import SmartContractGrid from '../components/SmartContractGrid'
import { useWeb3React } from '@web3-react/core'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {active} = useWeb3React();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p style={{ "fontSize": "1rem"}}>
            Welcome To Gas Free DApp 
          </p>
          <div style={{ "fontSize": "1rem"}}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              Malay
            </a>
          </div>
        </div>
        <div style={{"marginTop": "8rem", "display": "flex", "flexDirection": "column", "gap": "32px"}}>
          <ConnectWalletGrid/>
          {active && <SmartContractGrid/>}
        </div>
      </main>
    </>
  )
}
